[2025-09-26 22:35:04,261: INFO: main]: Starting the CNN Classifier application...
[2025-09-26 22:42:15,795: INFO: main]: Starting the CNN Classifier application...
[2025-09-26 22:42:41,277: INFO: main]: Starting the CNN Classifier application...
[2025-09-27 01:47:27,048: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 01:47:27,057: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 01:51:11,134: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 01:51:11,136: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 01:51:46,794: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 01:51:46,796: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 01:51:46,799: INFO: common]: Created directory at: artifacts
[2025-09-27 01:51:46,802: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 01:51:46,804: INFO: 2108146548]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 01:55:47,667: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 01:55:47,670: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 01:55:47,673: INFO: common]: Created directory at: artifacts
[2025-09-27 01:55:47,674: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 01:55:47,678: INFO: 2108146548]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:00:26,990: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:00:26,993: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:00:26,996: INFO: common]: Created directory at: artifacts
[2025-09-27 02:00:26,998: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:00:27,000: INFO: 3513763619]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:01:06,586: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:01:06,589: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:01:06,591: INFO: common]: Created directory at: artifacts
[2025-09-27 02:01:06,594: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:01:06,596: INFO: 2789812827]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:02:18,786: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:02:18,788: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:02:18,791: INFO: common]: Created directory at: artifacts
[2025-09-27 02:02:18,794: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:02:18,795: INFO: 2071522955]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:04:33,205: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:04:33,208: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:04:33,211: INFO: common]: Created directory at: artifacts
[2025-09-27 02:04:33,213: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:04:33,215: INFO: 2071522955]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:04:42,027: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:04:42,030: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:04:42,033: INFO: common]: Created directory at: artifacts
[2025-09-27 02:04:42,035: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:04:42,037: INFO: 3050489163]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:07:27,655: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:07:27,659: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:07:27,661: INFO: common]: Created directory at: artifacts
[2025-09-27 02:07:27,668: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:07:27,671: INFO: 2846847418]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:09:06,002: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:09:06,005: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:09:06,009: INFO: common]: Created directory at: artifacts
[2025-09-27 02:09:06,013: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:09:06,015: INFO: 3097298046]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:11:46,486: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:11:46,489: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:11:46,492: INFO: common]: Created directory at: artifacts
[2025-09-27 02:11:46,496: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:11:46,499: INFO: 2746166564]: Downloading file from :[https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link] to :[artifacts\data_injection\data.zip]
[2025-09-27 23:19:37,993: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:19:38,001: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:19:38,004: INFO: common]: Created directory at: artifacts
[2025-09-27 23:19:38,006: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:19:38,010: INFO: 2746166564]: Downloading file from :[https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link] to :[artifacts\data_injection\data.zip]
[2025-09-27 23:23:08,847: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:23:08,850: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:23:08,853: INFO: common]: Created directory at: artifacts
[2025-09-27 23:23:08,855: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:23:08,858: INFO: 2746166564]: Downloading file from :[https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link] to :[artifacts\data_injection\data.zip]
[2025-09-27 23:26:11,655: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:26:11,658: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:26:11,660: INFO: common]: Created directory at: artifacts
[2025-09-27 23:26:11,663: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:26:11,665: INFO: 2069769915]: Downloading file from :[https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link] to :[artifacts\data_injection\data.zip]
[2025-09-27 23:27:08,490: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:27:08,492: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:27:08,495: INFO: common]: Created directory at: artifacts
[2025-09-27 23:27:08,499: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:27:08,504: INFO: 2069769915]: File already exists of size :[~ 104 KB]
[2025-09-27 23:27:13,266: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:27:13,269: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:27:13,271: INFO: common]: Created directory at: artifacts
[2025-09-27 23:27:13,273: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:27:13,276: INFO: 2069769915]: File already exists of size :[~ 104 KB]
[2025-09-27 23:27:24,057: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:27:24,060: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:27:24,062: INFO: common]: Created directory at: artifacts
[2025-09-27 23:27:24,064: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:27:24,067: INFO: 2069769915]: File already exists of size :[~ 104 KB]
[2025-09-27 23:37:08,051: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:37:08,053: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:37:08,056: INFO: common]: Created directory at: artifacts
[2025-09-27 23:37:08,058: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:37:08,061: INFO: 3970809810]: File already exists of size: [~ 104 KB]
[2025-09-27 23:41:39,985: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:41:39,988: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:41:39,992: INFO: common]: Created directory at: artifacts
[2025-09-27 23:41:40,095: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:41:40,099: INFO: 3970809810]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-09-27 23:46:47,744: INFO: 3970809810]: Extracted zip file to: artifacts\data_injection
[2025-09-28 12:48:18,512: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 12:48:18,540: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 12:48:18,543: INFO: common]: Created directory at: artifacts
[2025-09-28 12:48:18,566: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 12:48:18,568: INFO: 113322524]: Downloading file from: https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=share_link
[2025-09-28 12:54:35,159: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 12:54:35,163: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 12:54:35,165: INFO: common]: Created directory at: artifacts
[2025-09-28 12:54:35,168: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 12:54:35,171: INFO: 2813457312]: Downloading file from: https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=share_link
[2025-09-28 12:56:32,672: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 12:56:32,674: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 12:56:32,677: INFO: common]: Created directory at: artifacts
[2025-09-28 12:56:32,680: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 12:56:32,684: INFO: 1482965000]: Downloading file from: https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1
[2025-09-28 13:01:49,362: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 13:01:49,365: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 13:01:49,368: INFO: common]: Created directory at: artifacts
[2025-09-28 13:01:49,370: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 13:01:49,373: INFO: 3970809810]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-09-28 13:08:27,482: INFO: 3970809810]: Extracted zip file to: artifacts\data_injection
[2025-09-28 16:06:16,381: ERROR: main]: name 'STAGE_NAME' is not defined
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 6, in <module>
    logger.info(f">>>>>>> Stage {STAGE_NAME} started <<<<<<<<")
NameError: name 'STAGE_NAME' is not defined
[2025-09-28 16:07:49,488: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-09-28 16:07:49,593: ERROR: main]: __init__() missing 1 required positional argument: 'config'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 9, in <module>
    obj = DataIngestionTrainingPipeline()
TypeError: __init__() missing 1 required positional argument: 'config'
[2025-09-28 16:09:30,883: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-09-28 16:09:30,883: ERROR: main]: __init__() missing 4 required positional arguments: 'root_dir', 'source_URL', 'local_data_file', and 'unzip_dir'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 10, in <module>
    obj = DataIngestionTrainingPipeline(DataInjectionConfig())
TypeError: __init__() missing 4 required positional arguments: 'root_dir', 'source_URL', 'local_data_file', and 'unzip_dir'
[2025-09-28 17:27:21,910: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-09-28 17:27:21,914: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:27:21,916: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:27:21,917: INFO: common]: Created directory at: artifacts
[2025-09-28 17:27:21,919: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 17:27:21,920: INFO: data_ingestion]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-09-28 17:34:54,186: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-09-28 17:34:54,190: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-01 22:44:23,950: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 22:44:23,983: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 22:44:23,987: INFO: common]: Created directory at: artifacts
[2025-10-01 22:44:23,990: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 22:49:14,115: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 22:49:14,119: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 22:49:14,121: INFO: common]: Created directory at: artifacts
[2025-10-01 22:49:14,123: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 22:55:16,719: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 22:55:16,725: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 22:55:16,731: INFO: common]: Created directory at: artifacts
[2025-10-01 22:55:16,734: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 22:59:12,424: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 22:59:12,430: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 22:59:12,434: INFO: common]: Created directory at: artifacts
[2025-10-01 22:59:12,438: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:00:07,076: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:00:07,080: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:00:07,083: INFO: common]: Created directory at: artifacts
[2025-10-01 23:00:07,087: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:00:36,848: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:00:36,852: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:00:36,855: INFO: common]: Created directory at: artifacts
[2025-10-01 23:00:36,857: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:01:04,472: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-01 23:12:41,795: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-01 23:12:41,797: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:12:41,799: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:12:41,800: INFO: common]: Created directory at: artifacts
[2025-10-01 23:12:41,801: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-01 23:12:41,801: INFO: data_ingestion]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-10-01 23:17:04,026: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-01 23:17:04,033: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-01 23:17:04,034: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-01 23:17:04,035: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:17:04,037: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:17:04,037: INFO: common]: Created directory at: artifacts
[2025-10-01 23:17:04,039: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:17:04,039: ERROR: main]: 'PrepareBaseModelConfig' object has no attribute 'params_include_top'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\components\prepare_base_model.py", line 15, in get_base_model
    include_top=self.config.params_include_top,
AttributeError: 'PrepareBaseModelConfig' object has no attribute 'params_include_top'
[2025-10-01 23:23:48,143: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-01 23:23:48,145: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:23:48,147: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:23:48,148: INFO: common]: Created directory at: artifacts
[2025-10-01 23:23:48,148: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-01 23:23:48,149: INFO: data_ingestion]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-10-01 23:29:33,668: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-01 23:29:33,672: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-01 23:29:33,672: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-01 23:29:33,674: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:29:33,675: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:29:33,675: INFO: common]: Created directory at: artifacts
[2025-10-01 23:29:33,677: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:29:33,677: ERROR: main]: __init__() got an unexpected keyword argument 'image_size'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'image_size'
[2025-10-02 00:08:12,435: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:08:12,438: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:08:12,440: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:08:12,441: INFO: common]: Created directory at: artifacts
[2025-10-02 00:08:12,442: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:08:12,444: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:09:16,230: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:09:16,233: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:09:16,234: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:09:16,237: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:09:16,238: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:09:16,239: INFO: common]: Created directory at: artifacts
[2025-10-02 00:09:16,239: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:09:16,240: ERROR: main]: PrepareBaseModelConfig() takes no arguments
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: PrepareBaseModelConfig() takes no arguments
[2025-10-02 00:14:23,728: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:14:23,731: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:14:23,733: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:14:23,735: INFO: common]: Created directory at: artifacts
[2025-10-02 00:14:23,735: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:14:23,737: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:15:28,559: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:15:28,565: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:15:28,566: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:15:28,569: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:15:28,574: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:15:28,575: INFO: common]: Created directory at: artifacts
[2025-10-02 00:15:28,575: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:15:28,576: ERROR: main]: PrepareBaseModelConfig() takes no arguments
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: PrepareBaseModelConfig() takes no arguments
[2025-10-02 00:20:02,655: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:20:02,657: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:20:02,659: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:20:02,660: INFO: common]: Created directory at: artifacts
[2025-10-02 00:20:02,662: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:20:02,662: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:21:19,361: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:21:19,439: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:21:19,439: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:21:19,444: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:21:19,447: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:21:19,448: INFO: common]: Created directory at: artifacts
[2025-10-02 00:21:19,449: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:21:19,449: ERROR: main]: PrepareBaseModelConfig() takes no arguments
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: PrepareBaseModelConfig() takes no arguments
[2025-10-02 00:33:19,072: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:33:19,074: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:33:19,076: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:33:19,076: INFO: common]: Created directory at: artifacts
[2025-10-02 00:33:19,077: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:33:19,078: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:34:22,862: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:34:22,954: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:34:22,954: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:34:22,956: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:34:22,957: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:34:22,958: INFO: common]: Created directory at: artifacts
[2025-10-02 00:34:22,959: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:34:22,959: ERROR: main]: PrepareBaseModelConfig() takes no arguments
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: PrepareBaseModelConfig() takes no arguments
[2025-10-02 00:37:36,884: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:37:36,886: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:37:36,887: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:37:36,888: INFO: common]: Created directory at: artifacts
[2025-10-02 00:37:36,888: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:37:36,888: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:38:41,538: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:38:41,543: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:38:41,543: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:38:41,546: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:38:41,548: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:38:41,550: INFO: common]: Created directory at: artifacts
[2025-10-02 00:38:41,550: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:38:41,550: ERROR: main]: __init__() got an unexpected keyword argument 'image_size'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'image_size'
[2025-10-02 00:43:06,766: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:43:06,768: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:43:06,772: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:43:06,774: INFO: common]: Created directory at: artifacts
[2025-10-02 00:43:06,776: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:43:06,777: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:44:11,300: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:44:11,322: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:44:11,322: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:44:11,406: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:44:11,408: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:44:11,410: INFO: common]: Created directory at: artifacts
[2025-10-02 00:44:11,410: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:44:12,017: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-02 00:44:13,767: INFO: main]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-02 02:29:17,150: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:29:17,155: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:29:17,158: INFO: common]: Created directory at: artifacts
[2025-10-02 02:31:09,546: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:31:09,552: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:31:09,554: INFO: common]: Created directory at: artifacts
[2025-10-02 02:31:09,558: INFO: common]: Created directory at: artifacts\training
[2025-10-02 02:47:56,655: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 02:47:56,658: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:47:56,659: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:47:56,660: INFO: common]: Created directory at: artifacts
[2025-10-02 02:47:56,660: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 02:47:56,660: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 02:48:47,822: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 02:48:47,826: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 02:48:47,826: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 02:48:47,829: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:48:47,831: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:48:47,832: INFO: common]: Created directory at: artifacts
[2025-10-02 02:48:47,833: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 02:48:48,557: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-02 02:48:51,039: INFO: main]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-02 02:48:51,040: INFO: main]: >>>>>>> Stage Training started <<<<<<<<
[2025-10-02 02:48:51,042: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:48:51,045: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:48:51,046: INFO: common]: Created directory at: artifacts
[2025-10-02 02:48:51,049: ERROR: main]: "'ConfigBox' object has no attribute 'data_ingestion'"
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'data_ingestion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'data_ingestion'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'data_ingestion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'data_ingestion'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'data_ingestion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'data_ingestion'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'data_ingestion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 33, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_03_model_training.py", line 13, in main
    training_config = config.get_training_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 46, in get_training_config
    training_data = os.path.join(self.config.data_ingestion.unzip_dir,"CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone")
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'data_ingestion'"
[2025-10-02 02:50:59,335: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 02:50:59,350: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:50:59,353: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:50:59,353: INFO: common]: Created directory at: artifacts
[2025-10-02 02:50:59,354: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 02:50:59,354: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 02:51:50,380: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 02:51:50,384: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 02:51:50,385: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 02:51:50,386: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:51:50,388: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:51:50,389: INFO: common]: Created directory at: artifacts
[2025-10-02 02:51:50,389: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 02:51:51,088: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-02 02:51:52,650: INFO: main]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-02 02:51:52,651: INFO: main]: >>>>>>> Stage Training started <<<<<<<<
[2025-10-02 02:51:52,653: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:51:52,655: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:51:52,656: INFO: common]: Created directory at: artifacts
[2025-10-02 02:51:52,656: INFO: common]: Created directory at: artifacts\training
[2025-10-02 03:36:53,947: INFO: main]: >>>>>>> Stage Training completed <<<<<<<<

x==========x
